### ISSUE TITLE
Add travis job to test against development versions of dependent packages

### ISSUE THREAD

**Issue by romainfrancois** [romainfrancois/dance#21]
`dplyr` has a job like that in its `.travis.yml` https://github.com/tidyverse/dplyr/blob/master/.travis.yml#L30

```
  - r: release
    env:
      - DEVEL_PACKAGES=true
    r_github_packages:
      - RcppCore/Rcpp
      - r-lib/rlang
      - tidyverse/tibble
      - tidyverse/tidyselect
```

The idea is that we can identify early when packages we depend on make changes that break `dance`.
